import {
  NewsArticle,
  EconomicNode,
  EconomicEdge,
  GraphData,
  Pathway,
  Prediction,
  DailySummary,
} from "./types";

export const mockArticles: NewsArticle[] = [
  {
    id: "art-1",
    title: "RBI Holds Repo Rate Steady at 6.5% Amid Inflation Concerns",
    summary:
      "The Reserve Bank of India maintained its benchmark lending rate at 6.5% for the eighth consecutive meeting, citing persistent food inflation risks while keeping growth outlook positive at 7% for FY25.",
    source: "Economic Times",
    url: "https://economictimes.com/rbi-policy",
    publishedAt: "2024-12-15T09:00:00Z",
    category: "economic",
    subcategory: "Indian National",
    economicImpactScore: 9,
    tags: ["RBI", "monetary policy", "repo rate", "inflation"],
  },
  {
    id: "art-2",
    title: "Sensex Crosses 75,000 Mark on Strong FII Inflows",
    summary:
      "Indian stock markets reached new highs as foreign institutional investors poured Rs 15,000 crore in December, driven by expectations of rate cuts in 2025 and robust corporate earnings.",
    source: "Mint",
    url: "https://livemint.com/markets",
    publishedAt: "2024-12-14T14:30:00Z",
    category: "economic",
    subcategory: "Indian National",
    economicImpactScore: 8,
    tags: ["stock market", "FII", "Sensex", "investment"],
  },
  {
    id: "art-3",
    title: "US Federal Reserve Signals Three Rate Cuts in 2025",
    summary:
      "The Federal Reserve indicated potential rate reductions totaling 75 basis points next year, boosting global market sentiment and strengthening emerging market currencies including the Indian rupee.",
    source: "Reuters",
    url: "https://reuters.com/fed-policy",
    publishedAt: "2024-12-13T20:00:00Z",
    category: "international",
    subcategory: "International",
    economicImpactScore: 9,
    tags: ["US Fed", "rate cuts", "global markets", "rupee"],
  },
  {
    id: "art-4",
    title: "India's GDP Growth Projected at 6.8% for Q3 FY25",
    summary:
      "Government estimates show robust economic expansion driven by manufacturing recovery and services sector growth, though agricultural output remains a concern due to uneven monsoon distribution.",
    source: "Business Standard",
    url: "https://business-standard.com/gdp",
    publishedAt: "2024-12-12T11:00:00Z",
    category: "economic",
    subcategory: "Indian National",
    economicImpactScore: 9,
    tags: ["GDP", "economic growth", "manufacturing", "services"],
  },
  {
    id: "art-5",
    title: "Maharashtra Assembly Passes Industrial Corridor Bill",
    summary:
      "The state legislature approved the Mumbai-Nagpur industrial corridor development bill, allocating Rs 50,000 crore for infrastructure development expected to create 2 million jobs over 5 years.",
    source: "Indian Express",
    url: "https://indianexpress.com/maharashtra",
    publishedAt: "2024-12-11T16:00:00Z",
    category: "political",
    subcategory: "Indian Local",
    economicImpactScore: 7,
    tags: ["infrastructure", "Maharashtra", "industrial corridor", "jobs"],
  },
  {
    id: "art-6",
    title: "OPEC+ Extends Production Cuts Through Q1 2025",
    summary:
      "Oil-producing nations agreed to maintain current output restrictions, keeping Brent crude above $80/barrel. India, as the world's third-largest oil importer, faces continued pressure on current account deficit.",
    source: "Bloomberg",
    url: "https://bloomberg.com/opec",
    publishedAt: "2024-12-10T08:00:00Z",
    category: "international",
    subcategory: "International",
    economicImpactScore: 8,
    tags: ["OPEC", "oil prices", "crude oil", "current account"],
  },
  {
    id: "art-7",
    title: "Tata Motors EV Sales Surge 45% in November",
    summary:
      "Tata Motors reported record electric vehicle sales of 8,500 units in November, capturing 62% market share in the Indian EV segment. The company announced plans for 3 new EV models in 2025.",
    source: "Autocar India",
    url: "https://autocarindia.com/tata-ev",
    publishedAt: "2024-12-09T10:30:00Z",
    category: "domestic",
    subcategory: "Indian National",
    economicImpactScore: 6,
    tags: ["EV", "Tata Motors", "automobile", "green energy"],
  },
  {
    id: "art-8",
    title: "China's Economic Slowdown Impacts Asian Supply Chains",
    summary:
      "China's manufacturing PMI fell to 48.2, signaling continued contraction. Indian manufacturers report increased orders as global companies diversify supply chains, benefiting sectors like electronics and pharmaceuticals.",
    source: "Financial Times",
    url: "https://ft.com/china-slowdown",
    publishedAt: "2024-12-08T07:00:00Z",
    category: "international",
    subcategory: "International",
    economicImpactScore: 8,
    tags: ["China", "supply chain", "manufacturing", "India opportunity"],
  },
  {
    id: "art-9",
    title: "Karnataka IT Sector Adds 50,000 Jobs in Q3",
    summary:
      "Bengaluru's technology sector showed strong hiring momentum with major companies including Infosys, Wipro, and startups expanding headcount, driven by AI and cloud computing demand.",
    source: "Deccan Herald",
    url: "https://deccanherald.com/karnataka-it",
    publishedAt: "2024-12-07T12:00:00Z",
    category: "domestic",
    subcategory: "Indian Local",
    economicImpactScore: 7,
    tags: ["IT sector", "employment", "Karnataka", "technology"],
  },
  {
    id: "art-10",
    title: "India-Middle East-Europe Corridor Agreement Advances",
    summary:
      "India signed implementation protocols for the IMEC trade corridor with UAE and Saudi Arabia, expected to reduce trade transit times by 40% and boost bilateral trade by $20 billion annually.",
    source: "The Hindu",
    url: "https://thehindu.com/imec",
    publishedAt: "2024-12-06T15:00:00Z",
    category: "political",
    subcategory: "International",
    economicImpactScore: 8,
    tags: ["IMEC", "trade corridor", "infrastructure", "geopolitics"],
  },
  {
    id: "art-11",
    title: "Rupee Strengthens to 82.5 Against Dollar on FII Flows",
    summary:
      "The Indian rupee appreciated against the US dollar supported by strong foreign investment inflows and positive trade balance data, with RBI intervention keeping volatility in check.",
    source: "NDTV Profit",
    url: "https://ndtv.com/rupee",
    publishedAt: "2024-12-05T09:30:00Z",
    category: "economic",
    subcategory: "Indian National",
    economicImpactScore: 7,
    tags: ["rupee", "forex", "FII", "trade balance"],
  },
  {
    id: "art-12",
    title: "Green Hydrogen Mission: First Production Facility Goes Online in Gujarat",
    summary:
      "India's first commercial green hydrogen plant began operations in Kutch, Gujarat with 50MW capacity. The facility is part of the National Green Hydrogen Mission targeting 5 MT annual production by 2030.",
    source: "Times of India",
    url: "https://timesofindia.com/green-hydrogen",
    publishedAt: "2024-12-04T11:00:00Z",
    category: "domestic",
    subcategory: "Indian Local",
    economicImpactScore: 7,
    tags: ["green hydrogen", "renewable energy", "Gujarat", "energy transition"],
  },
  {
    id: "art-13",
    title: "Food Inflation Rises to 8.7% on Vegetable Price Spike",
    summary:
      "Consumer food price index jumped due to unseasonal rains damaging vegetable crops, particularly tomatoes and onions. Government considering import duty reductions to stabilize prices.",
    source: "Business Today",
    url: "https://businesstoday.com/inflation",
    publishedAt: "2024-12-03T08:00:00Z",
    category: "economic",
    subcategory: "Indian National",
    economicImpactScore: 8,
    tags: ["inflation", "food prices", "agriculture", "consumer prices"],
  },
  {
    id: "art-14",
    title: "European Central Bank Cuts Rates by 25bps",
    summary:
      "ECB reduced its deposit facility rate to 3.75% amid slowing Eurozone growth. The move aligns with global easing expectations and supports risk appetite for emerging market assets.",
    source: "Reuters",
    url: "https://reuters.com/ecb-rate",
    publishedAt: "2024-12-02T14:00:00Z",
    category: "international",
    subcategory: "International",
    economicImpactScore: 7,
    tags: ["ECB", "rate cut", "Eurozone", "global liquidity"],
  },
  {
    id: "art-15",
    title: "UPI Transactions Hit 15 Billion Monthly Record",
    summary:
      "India's Unified Payments Interface processed over 15 billion transactions in November worth Rs 18 lakh crore, demonstrating the deepening of digital payments penetration across tier-2 and tier-3 cities.",
    source: "Mint",
    url: "https://livemint.com/upi-record",
    publishedAt: "2024-12-01T10:00:00Z",
    category: "domestic",
    subcategory: "Indian National",
    economicImpactScore: 6,
    tags: ["UPI", "digital payments", "fintech", "financial inclusion"],
  },
  {
    id: "art-16",
    title: "Tamil Nadu Semiconductor Fab Project Gets Environmental Clearance",
    summary:
      "The Ministry of Environment approved the Foxconn-HCL semiconductor fabrication unit near Chennai, a Rs 91,000 crore investment expected to position India in the global chip supply chain.",
    source: "The Hindu",
    url: "https://thehindu.com/semiconductor",
    publishedAt: "2024-11-30T13:00:00Z",
    category: "political",
    subcategory: "Indian Local",
    economicImpactScore: 9,
    tags: ["semiconductor", "manufacturing", "Tamil Nadu", "supply chain"],
  },
  {
    id: "art-17",
    title: "India's Goods Exports Cross $38 Billion in November",
    summary:
      "Merchandise exports rose 7.2% YoY driven by electronics, engineering goods, and pharmaceuticals. The trade deficit narrowed to $17 billion as oil import bill declined.",
    source: "Economic Times",
    url: "https://economictimes.com/exports",
    publishedAt: "2024-11-29T09:00:00Z",
    category: "economic",
    subcategory: "Indian National",
    economicImpactScore: 7,
    tags: ["exports", "trade balance", "manufacturing", "electronics"],
  },
  {
    id: "art-18",
    title: "Global AI Race: India Launches IndiaAI Compute Mission",
    summary:
      "The government allocated Rs 10,000 crore for AI compute infrastructure including 10,000 GPU clusters, aiming to make India a global AI hub and attract research investments from tech giants.",
    source: "Indian Express",
    url: "https://indianexpress.com/indiaai",
    publishedAt: "2024-11-28T16:00:00Z",
    category: "political",
    subcategory: "Indian National",
    economicImpactScore: 8,
    tags: ["AI", "technology policy", "compute", "digital infrastructure"],
  },
  {
    id: "art-19",
    title: "Geopolitical Tensions: Red Sea Shipping Disruptions Continue",
    summary:
      "Ongoing Houthi attacks in the Red Sea have forced major shipping companies to reroute via Cape of Good Hope, increasing India's import costs by 15-20% for European goods and adding 10-12 days transit time.",
    source: "Bloomberg",
    url: "https://bloomberg.com/red-sea",
    publishedAt: "2024-11-27T07:30:00Z",
    category: "international",
    subcategory: "International",
    economicImpactScore: 7,
    tags: ["geopolitics", "shipping", "trade disruption", "supply chain"],
  },
  {
    id: "art-20",
    title: "Mumbai Real Estate: Housing Sales Up 22% in 2024",
    summary:
      "Mumbai Metropolitan Region recorded highest-ever housing sales of 1.4 lakh units in 2024, driven by infrastructure projects like Metro lines and coastal road, pushing property prices up 12-15%.",
    source: "Times of India",
    url: "https://timesofindia.com/mumbai-realestate",
    publishedAt: "2024-11-26T11:30:00Z",
    category: "domestic",
    subcategory: "Indian Local",
    economicImpactScore: 6,
    tags: ["real estate", "Mumbai", "housing", "infrastructure"],
  },
  {
    id: "art-21",
    title: "PLI Scheme: Electronics Manufacturing Crosses $100 Billion",
    summary:
      "India's electronics manufacturing output hit the $100 billion milestone, with mobile phone production accounting for 45%. Apple's iPhone exports from India crossed $10 billion mark.",
    source: "Business Standard",
    url: "https://business-standard.com/pli",
    publishedAt: "2024-11-25T14:00:00Z",
    category: "economic",
    subcategory: "Indian National",
    economicImpactScore: 8,
    tags: ["PLI scheme", "electronics", "manufacturing", "Apple"],
  },
  {
    id: "art-22",
    title: "Climate Change: India Faces 5th Hottest Year on Record",
    summary:
      "IMD data shows 2024 was among the warmest years for India, with extreme weather events causing Rs 2 lakh crore in agricultural losses and accelerating the push for climate adaptation measures.",
    source: "Down to Earth",
    url: "https://downtoearth.org/climate",
    publishedAt: "2024-11-24T08:00:00Z",
    category: "domestic",
    subcategory: "Indian National",
    economicImpactScore: 7,
    tags: ["climate change", "agriculture", "extreme weather", "food security"],
  },
];

export const mockNodes: EconomicNode[] = mockArticles.map((article) => ({
  id: article.id,
  articleId: article.id,
  label: article.title.substring(0, 40) + "...",
  category: article.category,
  val: article.economicImpactScore,
  color:
    article.category === "domestic"
      ? "#22c55e"
      : article.category === "international"
      ? "#3b82f6"
      : article.category === "economic"
      ? "#f59e0b"
      : "#ef4444",
}));

export const mockEdges: EconomicEdge[] = [
  { source: "art-1", target: "art-2", strength: 0.9, relationship: "RBI policy directly impacts market sentiment and FII flows" },
  { source: "art-3", target: "art-2", strength: 0.85, relationship: "US Fed signals drive global FII allocation to India" },
  { source: "art-3", target: "art-11", strength: 0.8, relationship: "Dollar weakness from Fed cuts strengthens rupee" },
  { source: "art-1", target: "art-13", strength: 0.7, relationship: "RBI rate decision linked to inflation management" },
  { source: "art-6", target: "art-13", strength: 0.6, relationship: "Oil prices impact transportation costs and food inflation" },
  { source: "art-6", target: "art-11", strength: 0.65, relationship: "Oil import bill affects trade balance and rupee value" },
  { source: "art-4", target: "art-9", strength: 0.7, relationship: "GDP growth driven by IT sector employment generation" },
  { source: "art-4", target: "art-17", strength: 0.75, relationship: "Manufacturing growth contributes to export expansion" },
  { source: "art-8", target: "art-17", strength: 0.8, relationship: "China slowdown redirects orders to Indian manufacturers" },
  { source: "art-8", target: "art-16", strength: 0.7, relationship: "Supply chain diversification accelerates India semiconductor plans" },
  { source: "art-5", target: "art-20", strength: 0.6, relationship: "Industrial corridor drives real estate demand in region" },
  { source: "art-10", target: "art-17", strength: 0.65, relationship: "Trade corridor improves export competitiveness" },
  { source: "art-10", target: "art-19", strength: 0.7, relationship: "IMEC provides alternative to disrupted Red Sea routes" },
  { source: "art-12", target: "art-22", strength: 0.6, relationship: "Green energy addresses climate change mitigation" },
  { source: "art-14", target: "art-3", strength: 0.75, relationship: "Global central banks moving in sync on rate easing" },
  { source: "art-14", target: "art-2", strength: 0.6, relationship: "ECB easing supports global risk appetite" },
  { source: "art-15", target: "art-4", strength: 0.5, relationship: "Digital payment growth indicates economic activity expansion" },
  { source: "art-16", target: "art-21", strength: 0.85, relationship: "Semiconductor fab supports electronics manufacturing targets" },
  { source: "art-18", target: "art-9", strength: 0.7, relationship: "AI mission drives IT sector hiring and growth" },
  { source: "art-19", target: "art-6", strength: 0.6, relationship: "Shipping disruptions compound oil price pressures" },
  { source: "art-21", target: "art-17", strength: 0.8, relationship: "Electronics manufacturing directly boosts export numbers" },
  { source: "art-22", target: "art-13", strength: 0.7, relationship: "Climate impacts on agriculture drive food price inflation" },
  { source: "art-7", target: "art-12", strength: 0.5, relationship: "EV adoption linked to broader green energy transition" },
  { source: "art-13", target: "art-1", strength: 0.8, relationship: "Food inflation influences RBI rate decisions" },
];

export const mockGraphData: GraphData = {
  nodes: mockNodes,
  links: mockEdges,
};

export const mockPathways: Pathway[] = [
  {
    id: "path-1",
    title: "US Fed Rate Cuts to Indian Market Rally",
    description: "How US monetary easing cascades through to Indian equity markets and economic growth",
    steps: [
      { id: "s1", description: "US Fed cuts rates by 75bps in 2025", level: "macro", confidence: 80 },
      { id: "s2", description: "Dollar weakens, FII flows increase to emerging markets", level: "macro", confidence: 75 },
      { id: "s3", description: "Rupee strengthens to 81-82 range", level: "meso", confidence: 65 },
      { id: "s4", description: "Lower import costs reduce input inflation", level: "meso", confidence: 60 },
      { id: "s5", description: "RBI gains room for 50bps rate cut in H2 2025", level: "macro", confidence: 55 },
      { id: "s6", description: "Credit growth accelerates, boosting consumption", level: "micro", confidence: 50 },
    ],
    probability: 65,
    timeframeWeeks: 40,
    impactLevel: "macro",
  },
  {
    id: "path-2",
    title: "China Slowdown to India Manufacturing Boom",
    description: "Supply chain diversification away from China benefits Indian manufacturing sector",
    steps: [
      { id: "s1", description: "China PMI remains below 50 through Q1 2025", level: "macro", confidence: 70 },
      { id: "s2", description: "Global companies accelerate China+1 strategy", level: "macro", confidence: 75 },
      { id: "s3", description: "India PLI scheme attracts $15B additional FDI", level: "meso", confidence: 55 },
      { id: "s4", description: "Electronics and pharma manufacturing capacity doubles", level: "meso", confidence: 45 },
      { id: "s5", description: "Export growth hits 15% YoY by Q4 2025", level: "micro", confidence: 40 },
    ],
    probability: 55,
    timeframeWeeks: 52,
    impactLevel: "macro",
  },
  {
    id: "path-3",
    title: "Food Inflation to Consumption Slowdown",
    description: "Persistent food inflation eroding purchasing power and slowing urban demand",
    steps: [
      { id: "s1", description: "Food inflation remains above 8% through Q1 2025", level: "micro", confidence: 60 },
      { id: "s2", description: "Rural wage growth lags inflation by 2-3%", level: "micro", confidence: 55 },
      { id: "s3", description: "FMCG volume growth declines to 3-4%", level: "meso", confidence: 50 },
      { id: "s4", description: "RBI delays rate cuts despite global easing", level: "macro", confidence: 45 },
      { id: "s5", description: "GDP growth moderates to 6.2% in Q4 FY25", level: "macro", confidence: 40 },
    ],
    probability: 40,
    timeframeWeeks: 20,
    impactLevel: "macro",
  },
  {
    id: "path-4",
    title: "Green Energy Transition Acceleration",
    description: "India's renewable energy investments creating new economic opportunities",
    steps: [
      { id: "s1", description: "Green hydrogen cost reaches $3/kg parity", level: "micro", confidence: 50 },
      { id: "s2", description: "Solar capacity additions exceed 30GW in 2025", level: "meso", confidence: 65 },
      { id: "s3", description: "Energy import bill reduces by $15B annually", level: "macro", confidence: 40 },
      { id: "s4", description: "Current account deficit narrows to 1% of GDP", level: "macro", confidence: 35 },
    ],
    probability: 45,
    timeframeWeeks: 78,
    impactLevel: "macro",
  },
];

export const mockPredictions: Prediction[] = [
  {
    id: "pred-1",
    title: "Sensex to reach 80,000 by March 2025",
    description: "Strong FII inflows and domestic earnings growth will drive markets to new highs",
    createdAt: "2024-11-01T00:00:00Z",
    targetDate: "2025-03-31T00:00:00Z",
    confidence: 72,
    status: "active",
    category: "economic",
  },
  {
    id: "pred-2",
    title: "RBI to cut repo rate by 25bps in April 2025",
    description: "Easing food inflation and global rate cuts will create room for monetary easing",
    createdAt: "2024-11-15T00:00:00Z",
    targetDate: "2025-04-30T00:00:00Z",
    confidence: 60,
    status: "active",
    category: "economic",
  },
  {
    id: "pred-3",
    title: "Rupee to strengthen below 82 against USD",
    description: "Dollar weakness post Fed cuts and strong FII flows will support rupee",
    createdAt: "2024-10-01T00:00:00Z",
    targetDate: "2025-06-30T00:00:00Z",
    confidence: 55,
    status: "active",
    category: "economic",
  },
  {
    id: "pred-4",
    title: "India electronics exports to cross $30B in FY25",
    description: "PLI scheme output and Apple production scaling will boost electronics exports",
    createdAt: "2024-09-01T00:00:00Z",
    targetDate: "2025-03-31T00:00:00Z",
    confidence: 68,
    status: "active",
    category: "domestic",
  },
  {
    id: "pred-5",
    title: "Crude oil to remain range-bound at $75-85",
    description: "OPEC cuts offset by weak Chinese demand keeping prices stable",
    createdAt: "2024-08-01T00:00:00Z",
    targetDate: "2025-03-31T00:00:00Z",
    confidence: 65,
    status: "correct",
    category: "international",
    outcome: "Brent crude traded between $76-83 in Q4 2024",
  },
  {
    id: "pred-6",
    title: "IT sector hiring to rebound in H2 FY25",
    description: "AI-driven demand and discretionary spending recovery to drive hiring",
    createdAt: "2024-07-01T00:00:00Z",
    targetDate: "2024-12-31T00:00:00Z",
    confidence: 62,
    status: "correct",
    category: "domestic",
    outcome: "Karnataka IT sector added 50,000 jobs in Q3, confirming rebound",
  },
  {
    id: "pred-7",
    title: "India GDP growth above 7% in Q2 FY25",
    description: "Strong services and manufacturing to drive above-consensus growth",
    createdAt: "2024-06-01T00:00:00Z",
    targetDate: "2024-09-30T00:00:00Z",
    confidence: 58,
    status: "incorrect",
    category: "economic",
    outcome: "GDP came in at 6.7% in Q2 due to government spending slowdown",
  },
];

export const mockDailySummary: DailySummary = {
  id: "summary-2024-12-15",
  date: "2024-12-15",
  headline: "Markets Consolidate at Highs as RBI Holds Rates; Global Easing Cycle Supports Risk Appetite",
  keyTakeaways: [
    "RBI maintained status quo on rates for 8th meeting, signaling data-dependent approach to future cuts",
    "Global central banks (Fed, ECB) moving toward easing, creating favorable liquidity conditions for India",
    "Food inflation remains the key domestic risk factor, with vegetable prices elevated due to weather disruptions",
    "China's manufacturing contraction continues to benefit India's export competitiveness in electronics and pharma",
    "Infrastructure spending (IMEC corridor, semiconductor fabs) positioning India for long-term structural growth",
    "Digital economy indicators (UPI volumes, EV sales) show broadening of India's modernization story",
  ],
  economicIndicators: [
    { name: "Sensex", value: "75,234", change: 1.2, trend: "up" },
    { name: "USD/INR", value: "82.50", change: -0.3, trend: "down" },
    { name: "Brent Crude", value: "$82.40", change: 0.5, trend: "up" },
    { name: "CPI Inflation", value: "5.5%", change: 0.2, trend: "up" },
    { name: "10Y Bond Yield", value: "7.18%", change: -0.05, trend: "down" },
    { name: "Gold (MCX)", value: "Rs 62,450", change: 0.8, trend: "up" },
  ],
  topClusters: [
    { id: "cluster-1", title: "Monetary Policy & Rate Expectations", articleCount: 5, category: "economic", impactScore: 9 },
    { id: "cluster-2", title: "Supply Chain Realignment to India", articleCount: 4, category: "international", impactScore: 8 },
    { id: "cluster-3", title: "Infrastructure & Industrial Development", articleCount: 4, category: "political", impactScore: 7 },
    { id: "cluster-4", title: "Food Security & Inflation Risks", articleCount: 3, category: "domestic", impactScore: 8 },
    { id: "cluster-5", title: "Digital & Green Economy Growth", articleCount: 4, category: "domestic", impactScore: 6 },
  ],
  overallSentiment: "bullish",
};
